title: Richard Wang
description: My personal website
theme: minima

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: prose
    values:
      layout: project

collections:
  projects:
    output: true
  prose:
    output: true
  screenwriting:
    output: true
